// =============================================================================
// shared/catalogs/engines/caterpillar.js
// Caterpillar industrial engines — C-series + 3500/3600 series.
// Источник: Cat Power Systems datasheets 2023-2024 (cat.com).
// =============================================================================

export const CATERPILLAR_ENGINES = [
  {
    id: 'cat-c9.3',
    manufacturer: 'Caterpillar', series: 'C', model: 'C9.3',
    cylinders: 6, displacement: 9.3,
    sfcLkWh: 0.225,
    emissionTier: 'Tier 3 / EU Stage IIIA',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.0,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 12,
    },
    source: 'Cat C9.3 datasheet',
    note: '6-цил. 9.3L, 200-300 кВА класс.',
  },
  {
    id: 'cat-c18',
    manufacturer: 'Caterpillar', series: 'C', model: 'C18',
    cylinders: 6, displacement: 18.1,
    sfcLkWh: 0.220,
    emissionTier: 'Tier 4 ready',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.0,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 12,
    },
    source: 'Cat C18 datasheet',
    note: '6-цил. 18L, 350-500 кВА класс. Mid-size DC standard.',
  },
  {
    id: 'cat-c32',
    manufacturer: 'Caterpillar', series: 'C', model: 'C32',
    cylinders: 12, displacement: 32.1,
    sfcLkWh: 0.210,
    emissionTier: 'Tier 4 Final',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.2,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 15,
    },
    source: 'Cat C32 datasheet',
    note: '12-цил. V-образный 32L, 800-1200 кВА класс. Large DC.',
  },
  {
    id: 'cat-3516b',
    manufacturer: 'Caterpillar', series: '3500', model: '3516B',
    cylinders: 16, displacement: 69,
    sfcLkWh: 0.205,
    emissionTier: 'Tier 2',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.5,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 30,
    },
    source: 'Cat 3516B datasheet',
    note: '16-цил. V-образный 69L, 1500-1800 кВА. Mission-critical class.',
  },
  {
    id: 'cat-3520c',
    manufacturer: 'Caterpillar', series: '3500', model: '3520C',
    cylinders: 20, displacement: 78,
    sfcLkWh: 0.202,
    emissionTier: 'Tier 2',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.5,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 30,
    },
    source: 'Cat 3520C datasheet',
    note: '20-цил. V-образный 78L, 2000+ кВА. Параллель до 16 ед. через EMCP4.',
  },
  {
    id: 'cat-c175-16',
    manufacturer: 'Caterpillar', series: 'C', model: 'C175-16',
    cylinders: 16, displacement: 85,
    sfcLkWh: 0.198,
    emissionTier: 'Tier 4 Final option',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.5,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 30,
    },
    source: 'Cat C175-16 datasheet',
    note: '16-цил. V-образный 85L, 2500+ кВА. Top of C175 family. Гипер-ЦОД.',
  },
];
