// =============================================================================
// shared/catalogs/engines/cummins.js
// Cummins industrial engines — QSB / QSL / QSX / QSK series.
// Источник: Cummins Power Generation datasheets 2023-2024.
// =============================================================================

export const CUMMINS_ENGINES = [
  {
    id: 'cummins-x2.5-g3',
    manufacturer: 'Cummins', series: 'X', model: 'X2.5-G3',
    cylinders: 4, displacement: 2.5,
    sfcLkWh: 0.245,
    emissionTier: 'EU Stage IIIA / Tier 3',
    aspiration: 'turbocharged',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.0,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 12,
    },
    source: 'Cummins X2.5-G3 datasheet',
    note: 'Малый двигатель для 25-50 кВА ДГУ.',
  },
  {
    id: 'cummins-qsl9-g7',
    manufacturer: 'Cummins', series: 'QSL', model: 'QSL9-G7',
    cylinders: 6, displacement: 8.9,
    sfcLkWh: 0.230,
    emissionTier: 'EU Stage IIIA',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.0,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 12,
    },
    source: 'Cummins QSL9-G7 datasheet',
    note: '6-цил. 8.9L, 200-275 кВА класс.',
  },
  {
    id: 'cummins-ntaa855-g7a',
    manufacturer: 'Cummins', series: 'NT', model: 'NTAA855-G7A',
    cylinders: 6, displacement: 14,
    sfcLkWh: 0.220,
    emissionTier: 'Tier 2',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.2,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 15,
    },
    source: 'Cummins NTAA855-G7A datasheet',
    note: '6-цил. 14L, 250-350 кВА класс.',
  },
  {
    id: 'cummins-qsx15-g8',
    manufacturer: 'Cummins', series: 'QSX', model: 'QSX15-G8',
    cylinders: 6, displacement: 15,
    sfcLkWh: 0.218,
    emissionTier: 'EU Stage IIIA',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.0,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 12,
    },
    source: 'Cummins QSX15-G8 datasheet',
    note: '6-цил. 15L, 350-500 кВА класс.',
  },
  {
    id: 'cummins-qsk23-g3',
    manufacturer: 'Cummins', series: 'QSK', model: 'QSK23-G3',
    cylinders: 12, displacement: 23,
    sfcLkWh: 0.208,
    emissionTier: 'EU Stage IIIA',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.2,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 15,
    },
    source: 'Cummins QSK23-G3 datasheet',
    note: '12-цил. V-образный 23L, 700-900 кВА класс.',
  },
  {
    id: 'cummins-qsk60-g3',
    manufacturer: 'Cummins', series: 'QSK', model: 'QSK60-G3 / G14 / G15',
    cylinders: 16, displacement: 60,
    sfcLkWh: 0.200,
    emissionTier: 'EU Stage IIIA / Tier 2',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.5,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 30,
    },
    source: 'Cummins QSK60-G3/G14/G15 datasheet',
    note: '16-цил. V-образный 60L, 1500-2250 кВА класс.',
  },
  {
    id: 'cummins-qsk78-g16',
    manufacturer: 'Cummins', series: 'QSK', model: 'QSK78-G16',
    cylinders: 18, displacement: 78,
    sfcLkWh: 0.196,
    emissionTier: 'Hybrid Tier 2/4',
    aspiration: 'turbocharged + aftercooled',
    derateProfile: {
      altBaselineM: 1500,
      altPerHundredPct: 1.5,
      tempBaselineC: 25,
      tempPer5Pct: 0,
      altShiftPerC: 30,
    },
    source: 'Cummins QSK78-G16 datasheet',
    note: '18-цил. V-образный 78L, 2500+ кВА класс. Гипер-ЦОД.',
  },
];
